AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nova Sonic - AppSync Events API for Real-time Audio Streaming'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  ProjectName:
    Type: String
    Default: nova-sonic
    Description: Project name for resource naming

Resources:
  # ============================================
  # AppSync Events API (for real-time pub/sub)
  # ============================================
  
  AppSyncEventsApi:
    Type: AWS::AppSync::Api
    Properties:
      Name: !Sub '${ProjectName}-events-${Environment}'
      EventConfig:
        AuthProviders:
          - AuthType: AWS_IAM
          - AuthType: API_KEY
        ConnectionAuthModes:
          - AuthType: API_KEY
        DefaultPublishAuthModes:
          - AuthType: API_KEY
        DefaultSubscribeAuthModes:
          - AuthType: API_KEY

  # API Key for AppSync Events
  AppSyncApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppSyncEventsApi.ApiId
      Description: !Sub 'API Key for ${ProjectName} AppSync Events'
      Expires: 1767225600  # Unix timestamp for 2026-01-01 (adjust as needed)

  # Channel Namespace for audio streaming
  AudioChannelNamespace:
    Type: AWS::AppSync::ChannelNamespace
    Properties:
      ApiId: !GetAtt AppSyncEventsApi.ApiId
      Name: audio
      PublishAuthModes:
        - AuthType: API_KEY
      SubscribeAuthModes:
        - AuthType: API_KEY

  # ============================================
  # DynamoDB Tables
  # ============================================
  
  # Chat History Table
  ChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-chat-history-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Sessions Table (for active session tracking)
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-sessions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # IAM Roles
  # ============================================

  # Role for ECS tasks to access AppSync and Bedrock
  NovaSonicTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-task-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock:InvokeModelWithBidirectionalStream
                Resource: 
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.nova-sonic-v1:0'
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.nova-2-sonic-v1:0'
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
        - PolicyName: AppSyncAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - appsync:EventPublish
                  - appsync:EventSubscribe
                  - appsync:EventConnect
                Resource: !Sub 'arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${AppSyncEventsApi.ApiId}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ChatHistoryTable.Arn
                  - !GetAtt SessionsTable.Arn
                  - !Sub '${ChatHistoryTable.Arn}/index/*'
                  - !Sub '${SessionsTable.Arn}/index/*'

  # Role for frontend/client access (can be used with Cognito or API Key)
  ClientAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-client-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: AppSyncClientAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - appsync:EventPublish
                  - appsync:EventSubscribe
                  - appsync:EventConnect
                Resource: !Sub 'arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${AppSyncEventsApi.ApiId}/*'

  # ============================================
  # Cognito (for unauthenticated guest access)
  # ============================================

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub '${ProjectName}_identity_pool_${Environment}'
      AllowUnauthenticatedIdentities: true

  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        unauthenticated: !GetAtt ClientAccessRole.Arn

Outputs:
  # AppSync Outputs
  AppSyncApiId:
    Description: AppSync Events API ID
    Value: !GetAtt AppSyncEventsApi.ApiId
    Export:
      Name: !Sub '${ProjectName}-appsync-api-id-${Environment}'

  AppSyncHttpEndpoint:
    Description: AppSync HTTP Endpoint
    Value: !GetAtt AppSyncEventsApi.Dns.Http
    Export:
      Name: !Sub '${ProjectName}-appsync-http-${Environment}'

  AppSyncRealtimeEndpoint:
    Description: AppSync Realtime (WebSocket) Endpoint
    Value: !GetAtt AppSyncEventsApi.Dns.Realtime
    Export:
      Name: !Sub '${ProjectName}-appsync-realtime-${Environment}'

  AppSyncApiKey:
    Description: AppSync API Key
    Value: !GetAtt AppSyncApiKey.ApiKey
    Export:
      Name: !Sub '${ProjectName}-appsync-api-key-${Environment}'

  # DynamoDB Outputs
  ChatHistoryTableName:
    Description: Chat History DynamoDB Table Name
    Value: !Ref ChatHistoryTable
    Export:
      Name: !Sub '${ProjectName}-chat-history-table-${Environment}'

  ChatHistoryTableArn:
    Description: Chat History DynamoDB Table ARN
    Value: !GetAtt ChatHistoryTable.Arn
    Export:
      Name: !Sub '${ProjectName}-chat-history-table-arn-${Environment}'

  SessionsTableName:
    Description: Sessions DynamoDB Table Name
    Value: !Ref SessionsTable
    Export:
      Name: !Sub '${ProjectName}-sessions-table-${Environment}'

  # IAM Role Outputs
  TaskRoleArn:
    Description: ECS Task Role ARN
    Value: !GetAtt NovaSonicTaskRole.Arn
    Export:
      Name: !Sub '${ProjectName}-task-role-arn-${Environment}'

  # Cognito Outputs
  CognitoIdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Sub '${ProjectName}-identity-pool-id-${Environment}'
