AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nova Sonic Production Phase 2 - Add ECS Service (after Docker image push)'

Parameters:
  ProjectName:
    Type: String
    Default: nova-sonic

  Environment:
    Type: String
    Default: production

Resources:
  # ============================================
  # ECS SERVICE - Requires Docker image in ECR!
  # ============================================

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ProjectName}-service-${Environment}'
      Cluster: 
        Fn::ImportValue: !Sub '${ProjectName}-cluster-arn'
      TaskDefinition: 
        Fn::ImportValue: !Sub '${ProjectName}-task-def'
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: !Sub '${ProjectName}-subnet1'
            - Fn::ImportValue: !Sub '${ProjectName}-subnet2'
          SecurityGroups:
            - Fn::ImportValue: !Sub '${ProjectName}-ecs-sg'
      LoadBalancers:
        - ContainerName: !Sub '${ProjectName}-app'
          ContainerPort: 3000
          TargetGroupArn: 
            Fn::ImportValue: !Sub '${ProjectName}-tg-arn'
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      HealthCheckGracePeriodSeconds: 600

Outputs:
  ECSServiceName:
    Description: ECS Service Name
    Value: !GetAtt ECSService.Name

  ECSServiceArn:
    Description: ECS Service ARN
    Value: !Ref ECSService
