AWSTemplateFormatVersion: '2010-09-09'
Description: 'KYPERIAN ADVISOR - Autonomous AI Wealth Manager Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Deployment environment
    
  PolygonApiKey:
    Type: String
    NoEcho: true
    Description: Polygon.io API Key
    
  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: Anthropic (Claude) API Key
    
  TelegramBotToken:
    Type: String
    NoEcho: true
    Default: ''
    Description: Telegram Bot Token (optional)
    
  TelegramChatId:
    Type: String
    Default: ''
    Description: Telegram Chat ID for notifications (optional)

Resources:
  # ============================================================
  # DYNAMODB TABLES
  # ============================================================
  
  PortfolioTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kyperian-${Environment}-portfolio'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: KYPERIAN

  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kyperian-${Environment}-conversations'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: KYPERIAN

  TradesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kyperian-${Environment}-trades'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: symbol
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: symbol-timestamp-index
          KeySchema:
            - AttributeName: symbol
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: KYPERIAN

  # ============================================================
  # IAM ROLES
  # ============================================================
  
  AdvisorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'kyperian-${Environment}-advisor-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-*'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-*/index/*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: KYPERIAN

  # ============================================================
  # LAMBDA FUNCTIONS
  # ============================================================
  
  AdvisorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'kyperian-${Environment}-advisor'
      Description: 'KYPERIAN ADVISOR - Autonomous AI Wealth Manager'
      Runtime: python3.11
      Handler: handler.lambda_handler
      Role: !GetAtt AdvisorLambdaRole.Arn
      MemorySize: 1024
      Timeout: 120
      Code:
        ZipFile: |
          # Placeholder - deploy actual code via update-function-code
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Deploy code via CLI'}
      Environment:
        Variables:
          POLYGON_API_KEY: !Ref PolygonApiKey
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_CHAT_ID: !Ref TelegramChatId
          DYNAMODB_SIGNALS_TABLE: !Sub 'kyperian-${Environment}-signals'
          DYNAMODB_DECISIONS_TABLE: !Sub 'kyperian-${Environment}-decisions'
          DYNAMODB_TRADES_TABLE: !Ref TradesTable
          DYNAMODB_PORTFOLIO_TABLE: !Ref PortfolioTable
          DYNAMODB_CONVERSATIONS_TABLE: !Ref ConversationsTable
          ENVIRONMENT: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: KYPERIAN

  TelegramBotFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'kyperian-${Environment}-telegram-bot'
      Description: 'KYPERIAN Telegram Bot Handler'
      Runtime: python3.11
      Handler: handler.lambda_handler
      Role: !GetAtt AdvisorLambdaRole.Arn
      MemorySize: 512
      Timeout: 30
      Code:
        ZipFile: |
          # Placeholder - deploy actual code via update-function-code
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Deploy code via CLI'}
      Environment:
        Variables:
          POLYGON_API_KEY: !Ref PolygonApiKey
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          ADVISOR_API_URL: !Sub 'https://${AdvisorApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
          ENVIRONMENT: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: KYPERIAN

  # ============================================================
  # API GATEWAY
  # ============================================================
  
  AdvisorApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'kyperian-${Environment}-advisor-api'
      ProtocolType: HTTP
      Description: 'KYPERIAN ADVISOR API'
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - '*'
      Tags:
        Environment: !Ref Environment
        Project: KYPERIAN

  AdvisorApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref AdvisorApi
      StageName: !Ref Environment
      AutoDeploy: true
      Tags:
        Environment: !Ref Environment
        Project: KYPERIAN

  AdvisorApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AdvisorApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt AdvisorFunction.Arn
      PayloadFormatVersion: '2.0'

  AdvisorApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AdvisorApi
      RouteKey: 'GET /{proxy+}'
      Target: !Sub 'integrations/${AdvisorApiIntegration}'

  AdvisorApiRoutePost:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AdvisorApi
      RouteKey: 'POST /{proxy+}'
      Target: !Sub 'integrations/${AdvisorApiIntegration}'

  AdvisorApiRouteRoot:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AdvisorApi
      RouteKey: 'GET /'
      Target: !Sub 'integrations/${AdvisorApiIntegration}'

  AdvisorApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AdvisorFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AdvisorApi}/*'

  # Telegram webhook endpoint
  TelegramApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AdvisorApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt TelegramBotFunction.Arn
      PayloadFormatVersion: '2.0'

  TelegramApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AdvisorApi
      RouteKey: 'POST /telegram/webhook'
      Target: !Sub 'integrations/${TelegramApiIntegration}'

  TelegramApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TelegramBotFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AdvisorApi}/*'

  # ============================================================
  # EVENTBRIDGE - SCHEDULED MONITORING
  # ============================================================
  
  MonitoringSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'kyperian-${Environment}-monitor-schedule'
      Description: 'Run autonomous monitoring every 5 minutes'
      ScheduleExpression: 'rate(5 minutes)'
      State: ENABLED
      Targets:
        - Id: AdvisorTarget
          Arn: !GetAtt AdvisorFunction.Arn
          Input: '{"source": "aws.events", "detail-type": "Scheduled Monitoring"}'

  MonitoringSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AdvisorFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MonitoringSchedule.Arn

  # Daily Digest - 4pm ET
  DigestSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'kyperian-${Environment}-digest-schedule'
      Description: 'Send daily digest at 4pm ET'
      ScheduleExpression: 'cron(0 21 ? * MON-FRI *)'  # 9pm UTC = 4pm ET
      State: ENABLED
      Targets:
        - Id: DigestTarget
          Arn: !GetAtt AdvisorFunction.Arn
          Input: '{"source": "aws.events", "detail-type": "Daily Digest"}'

  DigestSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AdvisorFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DigestSchedule.Arn

  # Morning Briefing - 8am ET
  MorningSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'kyperian-${Environment}-morning-schedule'
      Description: 'Send morning briefing at 8am ET'
      ScheduleExpression: 'cron(0 13 ? * MON-FRI *)'  # 1pm UTC = 8am ET
      State: ENABLED
      Targets:
        - Id: MorningTarget
          Arn: !GetAtt AdvisorFunction.Arn
          Input: '{"source": "aws.events", "detail-type": "Morning Briefing"}'

  MorningSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AdvisorFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MorningSchedule.Arn

  # ============================================================
  # CLOUDWATCH ALARMS
  # ============================================================
  
  AdvisorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'kyperian-${Environment}-advisor-errors'
      AlarmDescription: 'Alert when Advisor function has errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AdvisorFunction

  AdvisorDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'kyperian-${Environment}-advisor-duration'
      AlarmDescription: 'Alert when Advisor function is slow'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 100000  # 100 seconds
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AdvisorFunction

Outputs:
  AdvisorApiUrl:
    Description: 'KYPERIAN ADVISOR API URL'
    Value: !Sub 'https://${AdvisorApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub 'kyperian-${Environment}-advisor-api-url'
      
  TelegramWebhookUrl:
    Description: 'Telegram Bot Webhook URL'
    Value: !Sub 'https://${AdvisorApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/telegram/webhook'
    Export:
      Name: !Sub 'kyperian-${Environment}-telegram-webhook-url'

  AdvisorFunctionArn:
    Description: 'Advisor Lambda ARN'
    Value: !GetAtt AdvisorFunction.Arn
    Export:
      Name: !Sub 'kyperian-${Environment}-advisor-function-arn'

  TelegramBotFunctionArn:
    Description: 'Telegram Bot Lambda ARN'
    Value: !GetAtt TelegramBotFunction.Arn
    Export:
      Name: !Sub 'kyperian-${Environment}-telegram-function-arn'
      
  PortfolioTableName:
    Description: 'Portfolio DynamoDB Table'
    Value: !Ref PortfolioTable
    
  TradesTableName:
    Description: 'Trades DynamoDB Table'
    Value: !Ref TradesTable
