AWSTemplateFormatVersion: '2010-09-09'
Description: 'KYPERIAN ELITE - API Gateway with WAF and Rate Limiting'

Parameters:
  Environment:
    Type: String
    Default: production
  
  NetworkStackName:
    Type: String
    Description: Name of the VPC CloudFormation stack
  
  SignalValidatorLambdaArn:
    Type: String
    Description: ARN of the Signal Validator Lambda function

Resources:
  # ============ API Gateway ============
  KyperianAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub kyperian-${Environment}-api
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - POST
          - GET
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
      Tags:
        Environment: !Ref Environment

  # ============ Lambda Integration ============
  SignalValidatorIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref KyperianAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref SignalValidatorLambdaArn
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 10000

  # ============ Routes ============
  WebhookRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref KyperianAPI
      RouteKey: POST /webhook
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  WebhookMTFRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref KyperianAPI
      RouteKey: POST /webhook/mtf
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  HealthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref KyperianAPI
      RouteKey: GET /health
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # ============ Stage ============
  ProductionStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref KyperianAPI
      StageName: !Ref Environment
      AutoDeploy: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50
      AccessLogSettings:
        DestinationArn: !GetAtt APIGatewayLogGroup.Arn
        Format: >-
          {"requestId":"$context.requestId","ip":"$context.identity.sourceIp",
          "requestTime":"$context.requestTime","httpMethod":"$context.httpMethod",
          "routeKey":"$context.routeKey","status":"$context.status",
          "responseLength":"$context.responseLength","integrationLatency":"$context.integrationLatency"}
      Tags:
        Environment: !Ref Environment

  # ============ Log Group ============
  APIGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/kyperian-${Environment}
      RetentionInDays: 30

  # ============ WAF ============
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub kyperian-${Environment}-waf
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub kyperian-${Environment}-waf
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
        
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRules
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
        
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BadInputs
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet

  # WAF Association with API Gateway
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub arn:aws:apigateway:${AWS::Region}::/apis/${KyperianAPI}/stages/${Environment}
      WebACLArn: !GetAtt WebACL.Arn

  # ============ API Key (Optional) ============
  # Add API Key authentication if needed for production

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${KyperianAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  ApiId:
    Description: API Gateway ID
    Value: !Ref KyperianAPI
    Export:
      Name: !Sub ${AWS::StackName}-ApiId

  WebACLArn:
    Description: WAF Web ACL ARN
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub ${AWS::StackName}-WebACLArn
