AWSTemplateFormatVersion: '2010-09-09'
Description: |
  NUBLE ELITE - Enterprise API Gateway
  ========================================
  High-performance HTTP API with:
  - WAF Web ACL with advanced rules
  - Custom domain support
  - Request/response logging
  - Rate limiting per client
  - JWT authentication (optional)
  - CloudWatch metrics and alarms

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production

  LambdaStackName:
    Type: String
    Description: Name of the Lambda CloudFormation stack

  DomainName:
    Type: String
    Default: ''
    Description: Custom domain name (optional)

  CertificateArn:
    Type: String
    Default: ''
    Description: ACM certificate ARN for custom domain (optional)

  ThrottlingBurstLimit:
    Type: Number
    Default: 500
    Description: API Gateway burst limit

  ThrottlingRateLimit:
    Type: Number
    Default: 200
    Description: API Gateway rate limit (requests per second)

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, '']]
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]
  CreateCustomDomain: !And [!Condition HasCustomDomain, !Condition HasCertificate]

Resources:
  # ============================================================
  # HTTP API GATEWAY
  # ============================================================
  
  NubleApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub nuble-${Environment}-api
      Description: NUBLE ELITE Trading Signal API
      ProtocolType: HTTP
      Version: '1.0'
      
      # CORS Configuration
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
          - X-Nuble-Source
          - X-Nuble-Timeframe
        ExposeHeaders:
          - X-Request-Id
          - X-Nuble-Latency
        MaxAge: 86400
      
      # Disable default endpoint if custom domain is used
      DisableExecuteApiEndpoint: !If [CreateCustomDomain, true, false]
      
      Tags:
        Environment: !Ref Environment
        Service: api-gateway

  # ============================================================
  # LAMBDA INTEGRATIONS
  # ============================================================
  
  SignalValidatorIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref NubleApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::ImportValue: !Sub ${LambdaStackName}-LambdaAliasArn
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 10000
      Description: Signal validator with provisioned concurrency

  # ============================================================
  # API ROUTES
  # ============================================================
  
  # Health Check Route
  HealthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref NubleApi
      RouteKey: GET /health
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # Main Webhook Route
  WebhookRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref NubleApi
      RouteKey: POST /webhook
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # MTF Webhook Route
  MTFWebhookRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref NubleApi
      RouteKey: POST /webhook/mtf
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # Signal by Symbol Route
  SignalBySymbolRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref NubleApi
      RouteKey: GET /signals/{symbol}
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # Decision Route
  DecisionRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref NubleApi
      RouteKey: GET /decision/{symbol}
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # Alignment Route
  AlignmentRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref NubleApi
      RouteKey: GET /alignment/{symbol}
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # Batch Signals Route
  BatchSignalsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref NubleApi
      RouteKey: POST /signals/batch
      AuthorizationType: NONE
      Target: !Sub integrations/${SignalValidatorIntegration}

  # ============================================================
  # API STAGE
  # ============================================================
  
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref NubleApi
      StageName: !Ref Environment
      AutoDeploy: true
      Description: !Sub ${Environment} stage with logging and throttling
      
      DefaultRouteSettings:
        ThrottlingBurstLimit: !Ref ThrottlingBurstLimit
        ThrottlingRateLimit: !Ref ThrottlingRateLimit
        DetailedMetricsEnabled: true
      
      AccessLogSettings:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","userAgent":"$context.identity.userAgent","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","path":"$context.path","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength","responseLatency":"$context.responseLatency","integrationLatency":"$context.integrationLatency","integrationStatus":"$context.integrationStatus","error":"$context.error.message","errorType":"$context.error.responseType"}'
      
      StageVariables:
        environment: !Ref Environment
      
      Tags:
        Environment: !Ref Environment

  # ============================================================
  # CLOUDWATCH LOGS
  # ============================================================
  
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/nuble-${Environment}-access
      RetentionInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================================
  # WAF WEB ACL
  # ============================================================
  
  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub nuble-${Environment}-waf
      Description: WAF protection for NUBLE API
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub nuble-${Environment}-waf
      
      Rules:
        # Rate limiting per IP
        - Name: RateLimitRule
          Priority: 1
          Action:
            Block:
              CustomResponse:
                ResponseCode: 429
                CustomResponseBodyKey: rate-limit-body
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
        
        # Block known bad IPs
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AmazonIpReputation
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
        
        # Common attack protection
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRules
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: SizeRestrictions_BODY
                - Name: CrossSiteScripting_BODY
        
        # SQL injection protection
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRules
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
        
        # Known bad inputs
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 5
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BadInputs
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
        
        # Allow TradingView IPs (example, add real IPs)
        - Name: AllowTradingViewIPs
          Priority: 0
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: TradingViewAllow
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt TradingViewIPSet.Arn
      
      CustomResponseBodies:
        rate-limit-body:
          ContentType: APPLICATION_JSON
          Content: '{"error": "rate_limit_exceeded", "message": "Too many requests. Please try again later."}'
      
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # IP Set for TradingView (add known IPs)
  TradingViewIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: !Sub nuble-${Environment}-tradingview-ips
      Description: Known TradingView webhook IP addresses
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses:
        - 52.89.214.238/32
        - 34.212.75.30/32
        - 54.218.53.128/32
        - 52.32.178.7/32
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # NOTE: WAF WebACL Association for HTTP API requires special handling
  # For now, we'll skip the association since HTTP APIs use a different integration method
  # WAF can be added via CloudFront distribution in front of API Gateway
  # WebAclAssociation:
  #   Type: AWS::WAFv2::WebACLAssociation
  #   DependsOn: ApiStage
  #   Properties:
  #     ResourceArn: !Sub arn:aws:apigateway:${AWS::Region}::/apis/${NubleApi}/stages/${Environment}
  #     WebACLArn: !GetAtt WebAcl.Arn

  # ============================================================
  # CUSTOM DOMAIN (Optional)
  # ============================================================
  
  CustomDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: CreateCustomDomain
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArn
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2
      Tags:
        Environment: !Ref Environment

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: CreateCustomDomain
    DependsOn: ApiStage
    Properties:
      ApiId: !Ref NubleApi
      DomainName: !Ref CustomDomainName
      Stage: !Ref Environment

  # ============================================================
  # CLOUDWATCH ALARMS
  # ============================================================
  
  Api4xxErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-api-4xx-errors
      AlarmDescription: High rate of 4xx errors
      MetricName: 4xx
      Namespace: AWS/ApiGateway
      Dimensions:
        - Name: ApiId
          Value: !Ref NubleApi
        - Name: Stage
          Value: !Ref Environment
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  Api5xxErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-api-5xx-errors
      AlarmDescription: High rate of 5xx errors
      MetricName: 5xx
      Namespace: AWS/ApiGateway
      Dimensions:
        - Name: ApiId
          Value: !Ref NubleApi
        - Name: Stage
          Value: !Ref Environment
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  ApiLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-api-latency
      AlarmDescription: API latency is too high
      MetricName: Latency
      Namespace: AWS/ApiGateway
      Dimensions:
        - Name: ApiId
          Value: !Ref NubleApi
        - Name: Stage
          Value: !Ref Environment
      ExtendedStatistic: p99
      Period: 60
      EvaluationPeriods: 3
      Threshold: 200
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  WafBlockedRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-waf-blocked
      AlarmDescription: High number of WAF blocked requests
      MetricName: BlockedRequests
      Namespace: AWS/WAFV2
      Dimensions:
        - Name: WebACL
          Value: !Sub nuble-${Environment}-waf
        - Name: Region
          Value: !Ref AWS::Region
        - Name: Rule
          Value: ALL
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

Outputs:
  ApiId:
    Description: API Gateway ID
    Value: !Ref NubleApi
    Export:
      Name: !Sub ${AWS::StackName}-ApiId

  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${NubleApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  ApiId:
    Description: API Gateway ID
    Value: !Ref NubleApi
    Export:
      Name: !Sub 'nuble-${Environment}-api-id'

  WebhookUrl:
    Description: Webhook URL for TradingView
    Value: !Sub https://${NubleApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/webhook
    Export:
      Name: !Sub ${AWS::StackName}-WebhookUrl

  MTFWebhookUrl:
    Description: MTF Webhook URL
    Value: !Sub https://${NubleApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/webhook/mtf
    Export:
      Name: !Sub ${AWS::StackName}-MTFWebhookUrl

  CustomDomainEndpoint:
    Condition: CreateCustomDomain
    Description: Custom domain endpoint
    Value: !Sub https://${DomainName}
    Export:
      Name: !Sub ${AWS::StackName}-CustomEndpoint

  WebAclArn:
    Description: WAF Web ACL ARN
    Value: !GetAtt WebAcl.Arn
    Export:
      Name: !Sub ${AWS::StackName}-WebAclArn

  AccessLogGroupArn:
    Description: Access log group ARN
    Value: !GetAtt ApiAccessLogGroup.Arn
    Export:
      Name: !Sub ${AWS::StackName}-AccessLogGroupArn
