AWSTemplateFormatVersion: '2010-09-09'
Description: >
  NUBLE Data Lake — S3 bucket with Glue Catalog for Athena queries,
  IAM roles for EC2/Lambda access, and CloudWatch monitoring.

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [production, staging]
  BucketName:
    Type: String
    Default: nuble-data-warehouse

Resources:

  # ─────────────────────────────────────────────
  # S3 Bucket (already exists — this manages its config)
  # ─────────────────────────────────────────────
  # Note: The bucket already exists. This template manages
  # the IAM roles, Glue catalog, and monitoring around it.

  # ─────────────────────────────────────────────
  # IAM Role — EC2/ECS instances accessing the data lake
  # ─────────────────────────────────────────────
  NubleDataAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'nuble-data-access-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ecs-tasks.amazonaws.com
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3DataLakeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Full access to the data warehouse bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:ListBucketMultipartUploads
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                Resource:
                  - !Sub 'arn:aws:s3:::${BucketName}'
                  - !Sub 'arn:aws:s3:::${BucketName}/*'
              # Athena query results
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::aws-athena-query-results-${AWS::AccountId}-${AWS::Region}'
                  - !Sub 'arn:aws:s3:::aws-athena-query-results-${AWS::AccountId}-${AWS::Region}/*'
        - PolicyName: GlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:BatchGetPartition
                Resource: '*'
        - PolicyName: AthenaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:StopQueryExecution
                Resource: '*'
      Tags:
        - Key: Project
          Value: nuble
        - Key: Environment
          Value: !Ref Environment

  # Instance profile for EC2
  NubleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'nuble-data-access-${Environment}'
      Roles:
        - !Ref NubleDataAccessRole

  # ─────────────────────────────────────────────
  # AWS Glue Catalog — Makes data queryable via Athena
  # ─────────────────────────────────────────────
  NubleGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub 'nuble_${Environment}'
        Description: NUBLE quantitative data lake — WRDS features, predictions, models

  # GKX Panel table (main feature panel)
  GkxPanelTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref NubleGlueDatabase
      TableInput:
        Name: gkx_panel
        Description: >
          Master GKX feature panel — 3.76M rows × 539 columns.
          Contains all cross-sectional stock features for ML predictions.
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          compressionType: snappy
        StorageDescriptor:
          Location: !Sub 's3://${BucketName}/features/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Columns:
            - Name: permno
              Type: bigint
              Comment: CRSP permanent security identifier
            - Name: date
              Type: timestamp
              Comment: Monthly observation date
            - Name: mvel1
              Type: double
              Comment: Market value of equity (millions)
            - Name: ret_excess_lead1m
              Type: double
              Comment: Forward 1-month excess return (prediction target)
            - Name: gsector
              Type: double
              Comment: GICS sector code
            - Name: bm
              Type: double
              Comment: Book-to-market ratio

  # Predictions table
  PredictionsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref NubleGlueDatabase
      TableInput:
        Name: predictions
        Description: ML model predictions by tier
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Location: !Sub 's3://${BucketName}/predictions/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe

  # Raw WRDS data table
  RawWrdsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref NubleGlueDatabase
      TableInput:
        Name: raw_wrds
        Description: Original WRDS data downloads (immutable)
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Location: !Sub 's3://${BucketName}/raw/wrds/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe

  # ─────────────────────────────────────────────
  # CloudWatch — Monitor S3 storage and access
  # ─────────────────────────────────────────────
  DataLakeDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub 'nuble-data-lake-${Environment}'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "S3 Bucket Size",
                "metrics": [
                  ["AWS/S3", "BucketSizeBytes", "BucketName", "${BucketName}", "StorageType", "StandardStorage"],
                  ["AWS/S3", "BucketSizeBytes", "BucketName", "${BucketName}", "StorageType", "IntelligentTieringStorage"]
                ],
                "period": 86400,
                "stat": "Average",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "S3 Object Count",
                "metrics": [
                  ["AWS/S3", "NumberOfObjects", "BucketName", "${BucketName}", "StorageType", "AllStorageTypes"]
                ],
                "period": 86400,
                "stat": "Average",
                "region": "${AWS::Region}"
              }
            }
          ]
        }

  # ─────────────────────────────────────────────
  # SNS Topic for alerts
  # ─────────────────────────────────────────────
  DataLakeAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'nuble-data-lake-alerts-${Environment}'
      Tags:
        - Key: Project
          Value: nuble

Outputs:
  DataAccessRoleArn:
    Description: IAM Role ARN for accessing the data lake
    Value: !GetAtt NubleDataAccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DataAccessRoleArn'

  InstanceProfileArn:
    Description: Instance Profile for EC2 data access
    Value: !GetAtt NubleInstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfileArn'

  GlueDatabaseName:
    Description: Glue catalog database name
    Value: !Ref NubleGlueDatabase
    Export:
      Name: !Sub '${AWS::StackName}-GlueDatabaseName'

  S3BucketUri:
    Description: S3 data lake URI
    Value: !Sub 's3://${BucketName}'

  AthenaQueryExample:
    Description: Example Athena query
    Value: !Sub >
      SELECT permno, date, mvel1, ret_excess_lead1m
      FROM nuble_${Environment}.gkx_panel
      WHERE date >= DATE '2020-01-01'
      ORDER BY mvel1 DESC
      LIMIT 100
