AWSTemplateFormatVersion: '2010-09-09'
Description: 'KYPERIAN ELITE - Decision Engine Stack (Multi-Timeframe Fusion + Notifications)'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
  
  TelegramBotToken:
    Type: String
    Default: ''
    NoEcho: true
    Description: 'Telegram Bot Token for notifications'
  
  TelegramChatId:
    Type: String
    Default: ''
    Description: 'Telegram Chat ID for notifications'
  
  DiscordWebhookUrl:
    Type: String
    Default: ''
    NoEcho: true
    Description: 'Discord Webhook URL for notifications'
  
  CheckIntervalMinutes:
    Type: Number
    Default: 5
    Description: 'How often to check for signal alignment (minutes)'

Resources:
  # ============================================================
  # IAM ROLE
  # ============================================================
  
  DecisionEngineLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'kyperian-${Environment}-decision-engine-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-signals'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-signals/index/*'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-decisions'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-decisions/index/*'
        
        - PolicyName: EventBridgeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/kyperian-${Environment}-signals'
        
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
                Condition:
                  StringEquals:
                    cloudwatch:namespace: KYPERIAN

  # ============================================================
  # LAMBDA FUNCTION
  # ============================================================
  
  DecisionEngineLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'kyperian-${Environment}-decision-engine'
      Description: 'Multi-timeframe signal fusion and notification engine'
      Runtime: python3.11
      Handler: handler.lambda_handler
      Role: !GetAtt DecisionEngineLambdaRole.Arn
      MemorySize: 512
      Timeout: 60
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DYNAMODB_SIGNALS_TABLE: !Sub 'kyperian-${Environment}-signals'
          DYNAMODB_DECISIONS_TABLE: !Sub 'kyperian-${Environment}-decisions'
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_CHAT_ID: !Ref TelegramChatId
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: kyperian-decision-engine
          POWERTOOLS_METRICS_NAMESPACE: KYPERIAN
      Code:
        ZipFile: |
          # Placeholder - will be replaced by actual deployment
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Deploy actual code'}
      Tags:
        - Key: Service
          Value: kyperian-decision-engine
        - Key: Environment
          Value: !Ref Environment

  # ============================================================
  # SCHEDULED EVENT (Every 5 minutes)
  # ============================================================
  
  ScheduledCheckRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'kyperian-${Environment}-alignment-check'
      Description: 'Check signal alignment every N minutes'
      ScheduleExpression: !Sub 'rate(${CheckIntervalMinutes} minutes)'
      State: ENABLED
      Targets:
        - Id: DecisionEngineLambda
          Arn: !GetAtt DecisionEngineLambda.Arn
  
  ScheduledCheckPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DecisionEngineLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledCheckRule.Arn

  # ============================================================
  # NEW SIGNAL TRIGGER (From EventBridge)
  # ============================================================
  
  NewSignalRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'kyperian-${Environment}-new-signal-trigger'
      Description: 'Trigger decision engine when new signal arrives'
      EventBusName: !Sub 'kyperian-${Environment}-signals'
      EventPattern:
        source:
          - kyperian.signals
        detail-type:
          - SignalReceived
      State: ENABLED
      Targets:
        - Id: DecisionEngineLambda
          Arn: !GetAtt DecisionEngineLambda.Arn
  
  NewSignalPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DecisionEngineLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt NewSignalRule.Arn

  # ============================================================
  # API GATEWAY INTEGRATION (Dashboard)
  # ============================================================
  
  DecisionApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: 
        Fn::ImportValue: !Sub 'kyperian-${Environment}-api-id'
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DecisionEngineLambda.Arn
      PayloadFormatVersion: '2.0'
  
  DashboardRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub 'kyperian-${Environment}-api-id'
      RouteKey: 'GET /dashboard'
      Target: !Sub 'integrations/${DecisionApiIntegration}'
  
  StatusRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub 'kyperian-${Environment}-api-id'
      RouteKey: 'GET /status'
      Target: !Sub 'integrations/${DecisionApiIntegration}'
  
  CheckSymbolRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub 'kyperian-${Environment}-api-id'
      RouteKey: 'GET /check/{symbol}'
      Target: !Sub 'integrations/${DecisionApiIntegration}'
  
  DecisionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DecisionEngineLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 
        - 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*'
        - ApiId:
            Fn::ImportValue: !Sub 'kyperian-${Environment}-api-id'

  # ============================================================
  # CLOUDWATCH DASHBOARD
  # ============================================================
  
  DecisionEngineDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub 'KYPERIAN-${Environment}-DecisionEngine'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Signal Alignment Checks",
                "metrics": [
                  ["KYPERIAN", "AlignmentChecks", "Service", "decision-engine"],
                  [".", "HighConfidenceSignals", ".", "."],
                  [".", "NotificationsSent", ".", "."]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Performance",
                "metrics": [
                  ["AWS/Lambda", "Duration", "FunctionName", "kyperian-${Environment}-decision-engine"],
                  [".", "Errors", ".", "."],
                  [".", "Invocations", ".", "."]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 6,
              "width": 24,
              "height": 6,
              "properties": {
                "title": "Recent Decisions",
                "query": "SOURCE '/aws/lambda/kyperian-${Environment}-decision-engine' | fields @timestamp, @message | filter @message like /Confidence:|ALIGNED|VETO/ | sort @timestamp desc | limit 50",
                "region": "${AWS::Region}"
              }
            }
          ]
        }

  # ============================================================
  # ALARMS
  # ============================================================
  
  DecisionEngineErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'kyperian-${Environment}-decision-engine-errors'
      AlarmDescription: 'Decision Engine Lambda errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref DecisionEngineLambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

Outputs:
  DecisionEngineLambdaArn:
    Description: 'Decision Engine Lambda ARN'
    Value: !GetAtt DecisionEngineLambda.Arn
    Export:
      Name: !Sub 'kyperian-${Environment}-decision-engine-arn'
  
  DecisionEngineLambdaName:
    Description: 'Decision Engine Lambda Name'
    Value: !Ref DecisionEngineLambda
    Export:
      Name: !Sub 'kyperian-${Environment}-decision-engine-name'
  
  DashboardUrl:
    Description: 'CloudWatch Dashboard URL'
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=KYPERIAN-${Environment}-DecisionEngine'
