AWSTemplateFormatVersion: '2010-09-09'
Description: 'KYPERIAN ELITE - Decision Engine Standalone Stack'

Parameters:
  Environment:
    Type: String
    Default: production
  
  ApiId:
    Type: String
    Description: 'Existing API Gateway ID (from kyperian-production-api stack)'
  
  TelegramBotToken:
    Type: String
    Default: ''
    NoEcho: true
  
  TelegramChatId:
    Type: String
    Default: ''
  
  DiscordWebhookUrl:
    Type: String
    Default: ''
    NoEcho: true

Resources:
  DecisionEngineLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'kyperian-${Environment}-decision-engine-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-signals'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-signals/index/*'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-decisions'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/kyperian-${Environment}-decisions/index/*'

  DecisionEngineLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'kyperian-${Environment}-decision-engine'
      Runtime: python3.11
      Handler: handler.lambda_handler
      Role: !GetAtt DecisionEngineLambdaRole.Arn
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DYNAMODB_SIGNALS_TABLE: !Sub 'kyperian-${Environment}-signals'
          DYNAMODB_DECISIONS_TABLE: !Sub 'kyperian-${Environment}-decisions'
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_CHAT_ID: !Ref TelegramChatId
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Deploy actual code'}

  ScheduledCheckRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'kyperian-${Environment}-alignment-check'
      ScheduleExpression: 'rate(5 minutes)'
      State: ENABLED
      Targets:
        - Id: DecisionEngineLambda
          Arn: !GetAtt DecisionEngineLambda.Arn

  ScheduledCheckPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DecisionEngineLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledCheckRule.Arn

  # API Gateway Integration
  DecisionApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiId
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DecisionEngineLambda.Arn
      PayloadFormatVersion: '2.0'

  DashboardRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiId
      RouteKey: 'GET /dashboard'
      Target: !Sub 'integrations/${DecisionApiIntegration}'

  CheckRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiId
      RouteKey: 'GET /check/{symbol}'
      Target: !Sub 'integrations/${DecisionApiIntegration}'

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DecisionEngineLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*'

Outputs:
  LambdaArn:
    Value: !GetAtt DecisionEngineLambda.Arn
  LambdaName:
    Value: !Ref DecisionEngineLambda
