AWSTemplateFormatVersion: '2010-09-09'
Description: 'NUBLE ELITE - ElastiCache Redis for Ultra-Low Latency Caching'

Parameters:
  Environment:
    Type: String
    Default: production
  
  NetworkStackName:
    Type: String
    Description: Name of the VPC CloudFormation stack
  
  CacheNodeType:
    Type: String
    Default: cache.t4g.micro
    Description: ElastiCache node type
    AllowedValues:
      - cache.t4g.micro
      - cache.t4g.small
      - cache.t4g.medium
      - cache.r6g.large
  
  NumCacheNodes:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 6

Resources:
  # ============ ElastiCache Subnet Group ============
  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for NUBLE Redis cache
      SubnetIds:
        - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet2
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============ ElastiCache Parameter Group ============
  CacheParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: Custom parameters for NUBLE Redis
      CacheParameterGroupFamily: redis7
      Properties:
        # Optimize for low latency
        tcp-keepalive: '300'
        timeout: '0'
        # Memory management
        maxmemory-policy: 'volatile-lru'
        # Disable persistence for speed
        appendonly: 'no'

  # ============ ElastiCache Replication Group ============
  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub nuble-${Environment}-redis
      ReplicationGroupDescription: NUBLE signal cache with automatic failover
      AutomaticFailoverEnabled: true
      MultiAZEnabled: true
      CacheNodeType: !Ref CacheNodeType
      CacheParameterGroupName: !Ref CacheParameterGroup
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      Engine: redis
      EngineVersion: '7.0'
      NumCacheClusters: !Ref NumCacheNodes
      Port: 6379
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${NetworkStackName}-RedisSecurityGroup
      # Encryption
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      # Maintenance
      PreferredMaintenanceWindow: sun:05:00-sun:06:00
      SnapshotRetentionLimit: 7
      SnapshotWindow: '03:00-04:00'
      # Auto minor version upgrade
      AutoMinorVersionUpgrade: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: nuble-cache

  # ============ SSM Parameter for Redis Endpoint ============
  RedisHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /nuble/redis/host
      Type: String
      Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
      Description: Redis primary endpoint for NUBLE
      Tags:
        Environment: !Ref Environment

  RedisPortParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /nuble/redis/port
      Type: String
      Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port
      Description: Redis port for NUBLE
      Tags:
        Environment: !Ref Environment

  # ============ CloudWatch Alarms ============
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-redis-cpu
      AlarmDescription: Redis CPU utilization alarm
      MetricName: CPUUtilization
      Namespace: AWS/ElastiCache
      Dimensions:
        - Name: CacheClusterId
          Value: !Sub ${RedisReplicationGroup}-001
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  MemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-redis-memory
      AlarmDescription: Redis memory utilization alarm
      MetricName: DatabaseMemoryUsagePercentage
      Namespace: AWS/ElastiCache
      Dimensions:
        - Name: CacheClusterId
          Value: !Sub ${RedisReplicationGroup}-001
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  ConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-redis-connections
      AlarmDescription: Redis current connections alarm
      MetricName: CurrConnections
      Namespace: AWS/ElastiCache
      Dimensions:
        - Name: CacheClusterId
          Value: !Sub ${RedisReplicationGroup}-001
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

Outputs:
  RedisEndpoint:
    Description: Redis Primary Endpoint
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-RedisEndpoint

  RedisPort:
    Description: Redis Port
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-RedisPort

  RedisReaderEndpoint:
    Description: Redis Reader Endpoint
    Value: !GetAtt RedisReplicationGroup.ReaderEndPoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-RedisReaderEndpoint
