AWSTemplateFormatVersion: '2010-09-09'
Description: |
  NUBLE ELITE - Lambda Stack (Simplified)
  Optimized for new AWS accounts with default limits

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production

  NetworkStackName:
    Type: String
    Description: Name of the VPC CloudFormation stack

  LambdaS3Bucket:
    Type: String
    Description: S3 bucket containing Lambda deployment package

  LambdaS3Key:
    Type: String
    Default: lambda/signal_validator.zip
    Description: S3 key for Lambda deployment package

Resources:
  # ============================================================
  # IAM ROLE
  # ============================================================
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub nuble-${Environment}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt SignalsTable.Arn
                  - !GetAtt DecisionsTable.Arn
                  - !Sub ${SignalsTable.Arn}/index/*
                  - !Sub ${DecisionsTable.Arn}/index/*
        
        - PolicyName: EventBridgeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  - !GetAtt SignalEventBus.Arn
        
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'

  # ============================================================
  # LAMBDA SECURITY GROUP
  # ============================================================
  
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId:
        Fn::ImportValue: !Sub ${NetworkStackName}-VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub nuble-${Environment}-lambda-sg

  # ============================================================
  # DYNAMODB TABLES
  # ============================================================
  
  SignalsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub nuble-${Environment}-signals
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: symbol
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: symbol-timestamp-index
          KeySchema:
            - AttributeName: symbol
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DecisionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub nuble-${Environment}-decisions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================================
  # EVENTBRIDGE
  # ============================================================
  
  SignalEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub nuble-${Environment}-signals

  # ============================================================
  # LAMBDA FUNCTION - Signal Validator
  # ============================================================
  
  SignalValidatorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub nuble-${Environment}-signal-validator
      Description: Ultra-fast signal validation for TradingView webhooks
      Runtime: python3.11
      Handler: handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      MemorySize: 512
      Timeout: 30
      Architectures:
        - arm64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet2
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DYNAMODB_SIGNALS_TABLE: !Ref SignalsTable
          DYNAMODB_DECISIONS_TABLE: !Ref DecisionsTable
          EVENTBRIDGE_BUS_NAME: !Ref SignalEventBus
      TracingConfig:
        Mode: Active
      Tags:
        - Key: Environment
          Value: !Ref Environment

  SignalValidatorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/nuble-${Environment}-signal-validator
      RetentionInDays: 30

  # Lambda Permission for API Gateway
  SignalValidatorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SignalValidatorFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

Outputs:
  SignalValidatorFunctionArn:
    Description: ARN of the Signal Validator Lambda function
    Value: !GetAtt SignalValidatorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SignalValidatorArn

  SignalValidatorFunctionName:
    Description: Name of the Signal Validator Lambda function
    Value: !Ref SignalValidatorFunction
    Export:
      Name: !Sub ${AWS::StackName}-SignalValidatorName

  SignalsTableName:
    Description: Name of the Signals DynamoDB table
    Value: !Ref SignalsTable
    Export:
      Name: !Sub ${AWS::StackName}-SignalsTable

  SignalsTableArn:
    Description: ARN of the Signals DynamoDB table
    Value: !GetAtt SignalsTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SignalsTableArn

  DecisionsTableName:
    Description: Name of the Decisions DynamoDB table
    Value: !Ref DecisionsTable
    Export:
      Name: !Sub ${AWS::StackName}-DecisionsTable

  DecisionsTableArn:
    Description: ARN of the Decisions DynamoDB table
    Value: !GetAtt DecisionsTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DecisionsTableArn

  EventBusArn:
    Description: ARN of the Signal EventBridge bus
    Value: !GetAtt SignalEventBus.Arn
    Export:
      Name: !Sub ${AWS::StackName}-EventBusArn

  LambdaSecurityGroupId:
    Description: Security Group ID for Lambda functions
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-LambdaSecurityGroup
