AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'NUBLE ELITE - Lambda Signal Validator (Target <10ms)'

Parameters:
  Environment:
    Type: String
    Default: production
  
  NetworkStackName:
    Type: String
    Description: Name of the VPC CloudFormation stack

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        POWERTOOLS_SERVICE_NAME: nuble-signal-validator

Resources:
  # ============ Lambda Function ============
  SignalValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub nuble-${Environment}-signal-validator
      Description: Ultra-fast signal validation for TradingView webhooks
      CodeUri: ../lambda/signal_validator/
      Handler: handler.lambda_handler
      Runtime: python3.11
      MemorySize: 1024  # More memory = faster CPU
      Timeout: 10
      ReservedConcurrentExecutions: 100
      
      # VPC Configuration for low latency
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${NetworkStackName}-ECSSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnet2
      
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          EVENTBRIDGE_BUS_NAME: !Ref SignalEventBus
          REDIS_HOST: '{{resolve:ssm:/nuble/redis/host}}'
          DYNAMODB_TABLE: !Ref SignalHistoryTable
      
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SignalHistoryTable
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref SignalEventBus
        - VPCAccessPolicy: {}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/nuble/*
      
      Tags:
        Environment: !Ref Environment
        Service: signal-validator

  # Lambda Permission for API Gateway
  SignalValidatorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SignalValidatorFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  # ============ EventBridge ============
  SignalEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub nuble-${Environment}-signals

  # Rule to route signals to ECS
  SignalToECSRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub nuble-${Environment}-signal-to-ecs
      EventBusName: !Ref SignalEventBus
      State: ENABLED
      EventPattern:
        source:
          - nuble.signal.validator
        detail-type:
          - SignalValidated
      Targets:
        - Id: ecs-target
          Arn: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
          # Will be routed to ECS via SQS or direct invocation

  # ============ DynamoDB Tables ============
  SignalHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub nuble-${Environment}-signals
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: symbol
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: symbol-timestamp-index
          KeySchema:
            - AttributeName: symbol
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DecisionHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub nuble-${Environment}-decisions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============ CloudWatch Alarms ============
  LatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-lambda-latency
      MetricName: Duration
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref SignalValidatorFunction
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 50  # 50ms threshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []  # Add SNS topic ARN for alerts
      TreatMissingData: notBreaching

  ErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-lambda-errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref SignalValidatorFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []  # Add SNS topic ARN for alerts
      TreatMissingData: notBreaching

Outputs:
  SignalValidatorFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt SignalValidatorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SignalValidatorArn

  SignalEventBusArn:
    Description: EventBridge Bus ARN
    Value: !GetAtt SignalEventBus.Arn
    Export:
      Name: !Sub ${AWS::StackName}-EventBusArn

  SignalHistoryTableArn:
    Description: DynamoDB Signals Table ARN
    Value: !GetAtt SignalHistoryTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SignalsTableArn

  DecisionHistoryTableArn:
    Description: DynamoDB Decisions Table ARN
    Value: !GetAtt DecisionHistoryTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DecisionsTableArn
