AWSTemplateFormatVersion: '2010-09-09'
Description: 'NUBLE ELITE - CloudWatch Monitoring Dashboard'

Parameters:
  Environment:
    Type: String
    Default: production
  
  LambdaFunctionName:
    Type: String
    Default: nuble-production-signal-validator
    Description: Name of the Signal Validator Lambda function
  
  ApiGatewayId:
    Type: String
    Description: API Gateway ID

  AlertEmail:
    Type: String
    Description: Email address for alerts
    Default: ''

Conditions:
  HasAlertEmail: !Not [!Equals [!Ref AlertEmail, '']]

Resources:
  # ============ SNS Topic for Alerts ============
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub nuble-${Environment}-alerts
      DisplayName: NUBLE Elite Alerts
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AlertEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlertEmail
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  # ============ Main Dashboard ============
  MainDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub NUBLE-${Environment}-Overview
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "text",
              "x": 0,
              "y": 0,
              "width": 24,
              "height": 1,
              "properties": {
                "markdown": "# 🚀 NUBLE ELITE - Real-Time Trading System Dashboard"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 1,
              "width": 8,
              "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${LambdaFunctionName}", {"stat": "Sum", "period": 300}]
                ],
                "view": "timeSeries",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 8,
              "y": 1,
              "width": 8,
              "height": 6,
              "properties": {
                "title": "Lambda Duration",
                "metrics": [
                  ["AWS/Lambda", "Duration", "FunctionName", "${LambdaFunctionName}", {"stat": "Average", "period": 300}]
                ],
                "view": "timeSeries",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 16,
              "y": 1,
              "width": 8,
              "height": 6,
              "properties": {
                "title": "Lambda Errors",
                "metrics": [
                  ["AWS/Lambda", "Errors", "FunctionName", "${LambdaFunctionName}", {"stat": "Sum", "period": 300}]
                ],
                "view": "timeSeries",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 7,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "API Gateway Requests",
                "metrics": [
                  ["AWS/ApiGateway", "Count", "ApiId", "${ApiGatewayId}", {"stat": "Sum", "period": 300}]
                ],
                "view": "timeSeries",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 7,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "API Gateway Latency",
                "metrics": [
                  ["AWS/ApiGateway", "Latency", "ApiId", "${ApiGatewayId}", {"stat": "Average", "period": 300}],
                  ["AWS/ApiGateway", "Latency", "ApiId", "${ApiGatewayId}", {"stat": "p99", "period": 300}]
                ],
                "view": "timeSeries",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 13,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "DynamoDB Read/Write",
                "metrics": [
                  ["AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "nuble-${Environment}-signals", {"stat": "Sum", "period": 300}],
                  ["AWS/DynamoDB", "ConsumedWriteCapacityUnits", "TableName", "nuble-${Environment}-signals", {"stat": "Sum", "period": 300}],
                  ["AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "nuble-${Environment}-decisions", {"stat": "Sum", "period": 300}],
                  ["AWS/DynamoDB", "ConsumedWriteCapacityUnits", "TableName", "nuble-${Environment}-decisions", {"stat": "Sum", "period": 300}]
                ],
                "view": "timeSeries",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 13,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Concurrent Executions",
                "metrics": [
                  ["AWS/Lambda", "ConcurrentExecutions", "FunctionName", "${LambdaFunctionName}", {"stat": "Maximum", "period": 300}]
                ],
                "view": "timeSeries",
                "region": "${AWS::Region}"
              }
            }
          ]
        }

  # ============ Critical Alarms ============
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-lambda-errors
      AlarmDescription: Lambda function is experiencing errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-lambda-throttles
      AlarmDescription: Lambda function is being throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-lambda-duration
      AlarmDescription: Lambda function duration is too high
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 25000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  API5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-api-5xx
      AlarmDescription: API Gateway 5xx errors
      MetricName: 5xx
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiId
          Value: !Ref ApiGatewayId
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  DynamoDBThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub nuble-${Environment}-dynamodb-throttle
      AlarmDescription: DynamoDB is being throttled
      MetricName: ThrottledRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: !Sub nuble-${Environment}-signals
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

Outputs:
  AlertTopicArn:
    Description: SNS Topic ARN for alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub ${AWS::StackName}-AlertTopicArn

  DashboardUrl:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=NUBLE-${Environment}-Overview
    Export:
      Name: !Sub ${AWS::StackName}-DashboardUrl
